// Real Teable client. Translates the mini-SQL dialect emitted by the data
// modules (and createRecord/updateRecord payloads) into Teable REST calls
// via teableFetch in src/lib/request.ts.
//
// Dialect supported (generated by qi()/lit()/qiTable() in ./sql.ts and ./tables.ts):
//   SELECT "col",... | COUNT(*) [AS alias]
//   FROM "<table-id>"
//   WHERE "col" = 'lit' | != | >= | <= | > | < num | "col" IS TRUE|FALSE|NULL|NOT NULL
//         | "col" ILIKE '%x%' | "col"::text LIKE '%x%'
//         | 1=1 | "col" > NOW() - INTERVAL '30 days'
//         | "__id" = 'x' | "__id" IN ('a','b') | "__id" IN (SELECT "link" FROM ...)
//   ORDER BY "col" ASC|DESC, ... (NULLS LAST ignored) LIMIT n OFFSET m
//
// fieldKeyType=name is used so record fields come back keyed by real labels,
// which are then mapped back to the app identifiers each module's parse fns expect.

import { teableFetch, isSafeWriteAllowed } from "@/lib/request";
import { FIELDS, type FieldMeta } from "./fields.generated";
import { DB_TABLES } from "./tables";

export const getTeableConfig = () => ({});

export type SqlRow = Record<string, unknown>;
export const qiTable = (table: string) => `"${table}"`;

/**
 * Extract the record id from a Teable link-field value. Teable may return a
 * single object ({id, title}), an array of such objects, or a plain id string.
 */
export function linkId(value: unknown): string | null {
  if (typeof value === "string") return value;
  if (Array.isArray(value) && value.length > 0) {
    const first = value[0] as { id?: unknown; __id?: unknown } | undefined;
    const id = first && (first.id ?? first.__id);
    return id != null ? String(id) : null;
  }
  if (value && typeof value === "object") {
    const obj = value as { id?: unknown; __id?: unknown };
    const id = obj.id ?? obj.__id;
    return id != null ? String(id) : null;
  }
  return null;
}

/** Extract the display title from a Teable link-field value (string or object). */
export function linkTitle(value: unknown): string | null {
  if (typeof value === "string") return value;
  if (Array.isArray(value) && value.length > 0) {
    const first = value[0] as { title?: unknown } | undefined;
    return first && first.title != null ? String(first.title) : null;
  }
  if (value && typeof value === "object") {
    const obj = value as { title?: unknown };
    return obj.title != null ? String(obj.title) : null;
  }
  return null;
}

/* ------------------------------------------------------------------ */
/* Schema index                                                        */
/* ------------------------------------------------------------------ */

interface TableContext {
  tableId: string;
  map: Map<string, FieldMeta>;
}

function buildSchema(): Map<string, TableContext> {
  const schema = new Map<string, TableContext>();
  for (const [appName, fields] of Object.entries(FIELDS)) {
    const tableId = (DB_TABLES as Record<string, string>)[appName];
    if (!tableId) continue;
    const map = new Map<string, FieldMeta>();
    for (const meta of Object.values(fields)) {
      map.set(meta.id, meta);
      if (meta.camel) map.set(meta.camel, meta);
      map.set(meta.real, meta);
    }
    schema.set(tableId, { tableId, map });
  }
  return schema;
}

const SCHEMA = buildSchema();

function resolveTable(ref: string): TableContext {
  const byApp = (DB_TABLES as Record<string, string>)[ref];
  const tableId = byApp ?? (SCHEMA.has(ref) ? ref : undefined);
  if (!tableId || !SCHEMA.has(tableId)) {
    throw new Error(`TeableClient: unknown table "${ref}"`);
  }
  return SCHEMA.get(tableId)!;
}

function lookupField(ctx: TableContext, key: string): FieldMeta | undefined {
  return ctx.map.get(key);
}

/* ------------------------------------------------------------------ */
/* SQL tokenizer / parser                                              */
/* ------------------------------------------------------------------ */

type SqlToken =
  | { type: "ident"; value: string }
  | { type: "string"; value: string }
  | { type: "number"; value: number }
  | { type: "word"; value: string }
  | { type: "op"; value: string }
  | { type: "punct"; value: string };

function tokenize(sql: string): SqlToken[] {
  const tokens: SqlToken[] = [];
  let i = 0;
  const n = sql.length;
  while (i < n) {
    const c = sql[i];
    if (/\s/.test(c)) {
      i++;
      continue;
    }
    if (c === '"') {
      let j = i + 1;
      let s = "";
      while (j < n && sql[j] !== '"') {
        if (sql[j] === '"' && sql[j + 1] === '"') {
          s += '"';
          j += 2;
          continue;
        }
        s += sql[j];
        j++;
      }
      tokens.push({ type: "ident", value: s });
      i = j + 1;
      continue;
    }
    if (c === "'") {
      let j = i + 1;
      let s = "";
      while (j < n && sql[j] !== "'") {
        if (sql[j] === "'" && sql[j + 1] === "'") {
          s += "'";
          j += 2;
          continue;
        }
        s += sql[j];
        j++;
      }
      tokens.push({ type: "string", value: s });
      i = j + 1;
      continue;
    }
    if (/[0-9]/.test(c) || (c === "-" && /[0-9]/.test(sql[i + 1] ?? ""))) {
      const m = /^-?(\d+\.?\d*|\.\d+)/.exec(sql.slice(i));
      if (!m) throw new Error(`TeableClient: bad number in SQL near '${sql.slice(i, i + 10)}'`);
      tokens.push({ type: "number", value: Number(m[0]) });
      i += m[0].length;
      continue;
    }
    const two = sql.slice(i, i + 2);
    if (two === "::") {
      tokens.push({ type: "op", value: "::" });
      i += 2;
      continue;
    }
    if (["!=", "<>", ">=", "<="].includes(two)) {
      tokens.push({ type: "op", value: two });
      i += 2;
      continue;
    }
    if (/^[=<>+\-]/.test(c)) {
      tokens.push({ type: "op", value: c });
      i += 1;
      continue;
    }
    if (c === "(" || c === ")" || c === "," || c === "*") {
      tokens.push({ type: "punct", value: c });
      i += 1;
      continue;
    }
    if (/[A-Za-z_]/.test(c)) {
      let j = i;
      while (j < n && /[A-Za-z0-9_]/.test(sql[j])) j++;
      tokens.push({ type: "word", value: sql.slice(i, j) });
      i = j;
      continue;
    }
    throw new Error(`TeableClient: unexpected character '${c}' in SQL`);
  }
  return tokens;
}

interface OrderByClause {
  field: string;
  order: "asc" | "desc";
}

type WhereClause =
  | { kind: "const" }
  | { kind: "isNull"; field: string; negated: boolean }
  | { kind: "isBool"; field: string; value: boolean }
  | { kind: "like"; field: string; pattern: string }
  | { kind: "compare"; field: string; op: string; value: string | number }
  | { kind: "dateRange"; field: string; op: string; interval: string }
  | { kind: "inList"; field: string; values: Array<string | number> }
  | { kind: "inSelect"; field: string; sub: SelectAst };

interface SelectAst {
  kind: "count" | "fields";
  alias?: string;
  fields: string[];
  table: string;
  where: WhereClause[];
  orderBy: OrderByClause[];
  limit: number | null;
  offset: number | null;
}

const COMPARE_OPS = ["=", "!=", "<>", ">", ">=", "<", "<="];

function normalizeOp(op: string): string {
  switch (op) {
    case "=":
      return "is";
    case "!=":
    case "<>":
      return "isNot";
    case ">":
      return "isGreater";
    case ">=":
      return "isGreaterEqual";
    case "<":
      return "isLess";
    case "<=":
      return "isLessEqual";
    default:
      throw new Error(`TeableClient: unsupported operator "${op}"`);
  }
}

class SqlParser {
  private tokens: SqlToken[];
  private pos = 0;

  constructor(sql: string) {
    this.tokens = tokenize(sql);
  }

  private peek(): SqlToken | null {
    return this.tokens[this.pos] ?? null;
  }

  private next(): SqlToken {
    const t = this.peek();
    if (!t) throw new Error("TeableClient: unexpected end of SQL");
    this.pos++;
    return t;
  }

  private isWord(w: string): boolean {
    const t = this.peek();
    return !!t && t.type === "word" && t.value.toUpperCase() === w;
  }

  private expectWord(w: string): void {
    const t = this.next();
    if (t.type !== "word" || t.value.toUpperCase() !== w) {
      throw new Error(`TeableClient: expected "${w}" in SQL, got "${t.value}"`);
    }
  }

  private peekPunct(p: string): boolean {
    const t = this.peek();
    return !!t && t.type === "punct" && t.value === p;
  }

  private expectPunct(p: string): void {
    if (!this.peekPunct(p)) {
      const t = this.peek();
      throw new Error(`TeableClient: expected "${p}" in SQL, got "${t?.value ?? "end"}"`);
    }
    this.next();
  }

  private parseQuotedIdent(): string {
    const t = this.next();
    if (t.type !== "ident") {
      throw new Error(`TeableClient: expected quoted identifier, got "${t.value ?? t.type}"`);
    }
    return t.value;
  }

  private parseNumber(): number {
    const t = this.next();
    if (t.type !== "number") {
      throw new Error(`TeableClient: expected number, got "${t.value ?? t.type}"`);
    }
    return t.value;
  }

  private parseValue(): string | number {
    const t = this.next();
    if (t.type === "string" || t.type === "number") return t.value;
    throw new Error("TeableClient: expected literal value in SQL");
  }

  parse(): SelectAst {
    this.expectWord("SELECT");
    let kind: "count" | "fields" = "fields";
    let alias: string | undefined;
    const fields: string[] = [];

    if (this.isWord("COUNT")) {
      this.next();
      this.expectPunct("(");
      this.expectPunct("*");
      this.expectPunct(")");
      kind = "count";
      if (this.isWord("AS")) {
        this.next();
        alias = this.next().value as string;
      } else if (this.peek()?.type === "word" || this.peek()?.type === "ident") {
        alias = this.next().value as string;
      }
      alias = alias ?? "count";
    } else {
      fields.push(this.parseQuotedIdent());
      while (this.peekPunct(",")) {
        this.next();
        fields.push(this.parseQuotedIdent());
      }
    }

    this.expectWord("FROM");
    const table = this.parseQuotedIdent();

    const where: WhereClause[] = [];
    if (this.isWord("WHERE")) {
      this.next();
      where.push(this.parseClause());
      while (this.isWord("AND")) {
        this.next();
        where.push(this.parseClause());
      }
    }

    const orderBy: OrderByClause[] = [];
    if (this.isWord("ORDER")) {
      this.next();
      this.expectWord("BY");
      orderBy.push(this.parseOrderByItem());
      while (this.peekPunct(",")) {
        this.next();
        orderBy.push(this.parseOrderByItem());
      }
    }

    let limit: number | null = null;
    if (this.isWord("LIMIT")) {
      this.next();
      limit = this.parseNumber();
    }
    let offset: number | null = null;
    if (this.isWord("OFFSET")) {
      this.next();
      offset = this.parseNumber();
    }

    return { kind, alias, fields, table, where, orderBy, limit, offset };
  }

  private parseOrderByItem(): OrderByClause {
    const field = this.parseQuotedIdent();
    let order: "asc" | "desc" = "asc";
    if (this.isWord("ASC")) {
      this.next();
      order = "asc";
    } else if (this.isWord("DESC")) {
      this.next();
      order = "desc";
    }
    if (this.isWord("NULLS")) {
      this.next();
      const w = this.next();
      if (w.type !== "word" || (w.value.toUpperCase() !== "FIRST" && w.value.toUpperCase() !== "LAST")) {
        throw new Error("TeableClient: expected FIRST/LAST after NULLS");
      }
    }
    return { field, order };
  }

  private parseClause(): WhereClause {
    const t0 = this.peek();
    if (!t0) throw new Error("TeableClient: missing WHERE clause");

    // 1 = 1 (no-op predicate)
    if (t0.type === "number") {
      const a = this.next();
      const b = this.next();
      const c = this.next();
      if (a.value === 1 && b.type === "op" && b.value === "=" && c.type === "number" && c.value === 1) {
        return { kind: "const" };
      }
      throw new Error("TeableClient: unsupported literal clause in SQL");
    }

    if (t0.type !== "ident") {
      throw new Error(`TeableClient: expected column in WHERE, got "${t0.value ?? t0.type}"`);
    }
    const field = this.next().value as string;

    // Optional Postgres-style cast: "col"::text
    if (this.peek()?.type === "op" && this.peek()!.value === "::") {
      this.next();
      this.expectWord("TEXT");
    }

    const opTok = this.next();
    const op: string = opTok.type === "word" ? String(opTok.value).toUpperCase() : String(opTok.value);

    if (op === "IS") {
      const w = this.next();
      const v = String(w.value).toUpperCase();
      if (v === "NOT") {
        this.expectWord("NULL");
        return { kind: "isNull", field, negated: true };
      }
      if (v === "NULL") return { kind: "isNull", field, negated: false };
      if (v === "TRUE") return { kind: "isBool", field, value: true };
      if (v === "FALSE") return { kind: "isBool", field, value: false };
      throw new Error(`TeableClient: unsupported IS "${w.value}" in SQL`);
    }

    if (op === "LIKE" || op === "ILIKE") {
      const s = this.next();
      if (s.type !== "string") throw new Error("TeableClient: LIKE expected a string pattern");
      return { kind: "like", field, pattern: s.value as string };
    }

    if (op === "IN") {
      this.expectPunct("(");
      if (this.isWord("SELECT")) {
        const sub = this.parse();
        this.expectPunct(")");
        return { kind: "inSelect", field, sub };
      }
      const values: Array<string | number> = [this.parseValue()];
      while (this.peekPunct(",")) {
        this.next();
        values.push(this.parseValue());
      }
      this.expectPunct(")");
      return { kind: "inList", field, values };
    }

    if (COMPARE_OPS.includes(op)) {
      const vTok = this.next();
      if (vTok.type === "string" || vTok.type === "number") {
        return { kind: "compare", field, op: normalizeOp(op), value: vTok.value };
      }
      if (vTok.type === "word" && String(vTok.value).toUpperCase() === "NOW") {
        this.expectPunct("(");
        this.expectPunct(")");
        const minus = this.next();
        if (minus.type !== "op" || minus.value !== "-") {
          throw new Error("TeableClient: expected '-' after NOW()");
        }
        this.expectWord("INTERVAL");
        const iv = this.next();
        if (iv.type !== "string") throw new Error("TeableClient: INTERVAL expected a string");
        return { kind: "dateRange", field, op: normalizeOp(op), interval: iv.value as string };
      }
      throw new Error("TeableClient: unsupported comparison value in SQL");
    }

    throw new Error(`TeableClient: unsupported WHERE keyword "${op}" in SQL`);
  }
}

/* ------------------------------------------------------------------ */
/* Dialect -> Teable filter translation                                */
/* ------------------------------------------------------------------ */

interface FilterPredicate {
  fieldId: string;
  operator: string;
  value?: unknown;
}

interface CompiledWhere {
  predicates: FilterPredicate[];
  selectedIds: string[];
  skipAll: boolean;
}

function parseIntervalDays(interval: string): number {
  const m = /\d+/.exec(interval);
  return m ? Number(m[0]) : 1;
}

function applyEnumIn(meta: FieldMeta, value: unknown): unknown {
  if (meta.enumIn && typeof value === "string") {
    const mapped = meta.enumIn[value];
    if (mapped != null) return mapped;
  }
  return value;
}

function translateCondition(meta: FieldMeta, c: WhereClause): FilterPredicate | null {
  switch (c.kind) {
    case "const":
    case "inSelect":
      return null;
    case "isBool":
      return { fieldId: meta.fieldId, operator: "is", value: c.value };
    case "isNull":
      return { fieldId: meta.fieldId, operator: c.negated ? "isNotEmpty" : "isEmpty" };
    case "like": {
      const sub = c.pattern.replace(/^%+|%+$/g, "");
      if (meta.type === "link") {
        return { fieldId: meta.fieldId, operator: "is", value: sub };
      }
      if (meta.type === "singleSelect" || meta.type === "text" || meta.type === "longText") {
        return { fieldId: meta.fieldId, operator: "contains", value: sub };
      }
      if (meta.type === "number") {
        const num = Number(sub);
        return { fieldId: meta.fieldId, operator: "is", value: Number.isFinite(num) ? num : 0 };
      }
      throw new Error(`TeableClient: LIKE not supported on ${meta.type} field ${meta.real}`);
    }
    case "compare": {
      if (meta.type === "checkbox") {
        const bool = c.value === 1 || String(c.value).toLowerCase() === "true";
        return { fieldId: meta.fieldId, operator: c.op === "isNot" ? "isNot" : "is", value: bool };
      }
      switch (meta.type) {
        case "text":
        case "longText":
        case "singleSelect": {
          if (c.op !== "is" && c.op !== "isNot") {
            throw new Error(`TeableClient: operator ${c.op} not supported on text field ${meta.real}`);
          }
          return { fieldId: meta.fieldId, operator: c.op, value: applyEnumIn(meta, c.value) };
        }
        case "number": {
          const num = typeof c.value === "number" ? c.value : Number(c.value);
          if (!Number.isFinite(num)) {
            throw new Error(`TeableClient: non-numeric compare on number field ${meta.real}`);
          }
          return { fieldId: meta.fieldId, operator: c.op, value: num };
        }
        case "link": {
          if (c.op === "is" || c.op === "isNot") {
            return { fieldId: meta.fieldId, operator: c.op, value: String(c.value) };
          }
          throw new Error(`TeableClient: operator ${c.op} not supported on link field ${meta.real}`);
        }
        case "createdTime":
        case "lastModifiedTime":
        case "date": {
          const iso = String(c.value);
          if (c.op === "is") return { fieldId: meta.fieldId, operator: "is", value: iso };
          if (c.op === "isGreater" || c.op === "isGreaterEqual") {
            return { fieldId: meta.fieldId, operator: "isOnOrAfter", value: iso };
          }
          if (c.op === "isLess" || c.op === "isLessEqual") {
            return { fieldId: meta.fieldId, operator: "isOnOrBefore", value: iso };
          }
          throw new Error(`TeableClient: operator ${c.op} not supported on date field ${meta.real}`);
        }
        default:
          throw new Error(`TeableClient: compare not supported on ${meta.type} field`);
      }
    }
    case "dateRange": {
      const days = parseIntervalDays(c.interval);
      const iso = new Date(Date.now() - days * 86_400_000).toISOString();
      const operator = c.op === "isLess" || c.op === "isLessEqual" ? "isOnOrBefore" : "isOnOrAfter";
      return { fieldId: meta.fieldId, operator, value: iso };
    }
    case "inList": {
      if (c.values.length === 1) {
        return { fieldId: meta.fieldId, operator: "is", value: applyEnumIn(meta, c.values[0]) };
      }
      throw new Error(`TeableClient: multi-value IN only supported on __id`);
    }
    default:
      throw new Error(`TeableClient: unhandled WHERE clause`);
  }
}

async function compileWhere(ctx: TableContext, clauses: WhereClause[]): Promise<CompiledWhere> {
  const predicates: FilterPredicate[] = [];
  const selectedIds: string[] = [];
  let skipAll = false;

  for (const c of clauses) {
    if (c.kind === "const") continue;

    if (c.kind === "inSelect" && c.field === "__id") {
      const subRows = await executeSelect(c.sub);
      const col = c.sub.fields[0];
      for (const row of subRows) {
        const v = row[col];
        if (Array.isArray(v)) {
          const id = (v[0] as { id?: unknown } | undefined)?.id;
          if (id) selectedIds.push(String(id));
        } else if (typeof v === "string") {
          selectedIds.push(v);
        }
      }
      continue;
    }

    if (c.kind === "inSelect") {
      throw new Error("TeableClient: IN (SELECT ...) is only supported on __id");
    }

    if (c.field === "__id") {
      if (c.kind === "compare" && c.op === "is") {
        selectedIds.push(String(c.value));
      } else if (c.kind === "inList") {
        for (const v of c.values) selectedIds.push(String(v));
      } else if (c.kind === "isNull") {
        skipAll = !c.negated; // __id IS NULL can never match
      }
      continue;
    }

    const meta = lookupField(ctx, c.field);
    if (!meta) {
      throw new Error(`TeableClient: no field mapping for "${c.field}" on table ${ctx.tableId}`);
    }
    const p = translateCondition(meta, c);
    if (p) predicates.push(p);
  }

  return { predicates, selectedIds, skipAll };
}

function compiledOrderBy(ctx: TableContext, clauses: OrderByClause[]): Array<{ fieldId: string; order: string }> {
  return clauses.map((o) => {
    const meta = lookupField(ctx, o.field);
    if (!meta) {
      throw new Error(`TeableClient: cannot ORDER BY unmapped field "${o.field}"`);
    }
    return { fieldId: meta.fieldId, order: o.order === "desc" ? "desc" : "asc" };
  });
}

/* ------------------------------------------------------------------ */
/* Execution                                                           */
/* ------------------------------------------------------------------ */

interface TeableRecord {
  id: string;
  fields: Record<string, unknown>;
}

interface TeableRecordResponse {
  records: TeableRecord[];
}

function buildQueryParams(options: {
  fieldKeyType?: string;
  signedUrl?: string;
  filter?: FilterPredicate[];
  orderBy?: Array<{ fieldId: string; order: string }>;
  take?: number | null;
  skip?: number | null;
  selectedIds?: string[];
}): URLSearchParams {
  const q = new URLSearchParams();
  if (options.fieldKeyType) q.set("fieldKeyType", options.fieldKeyType);
  if (options.signedUrl) q.set("signedUrl", "true");
  if (options.filter && options.filter.length > 0) {
    q.set("filter", JSON.stringify({ conjunction: "and", filterSet: options.filter }));
  }
  if (options.orderBy && options.orderBy.length > 0) {
    q.set("orderBy", JSON.stringify(options.orderBy));
  }
  if (options.take != null) q.set("take", String(options.take));
  if (options.skip != null) q.set("skip", String(options.skip));
  for (const id of options.selectedIds ?? []) q.append("selectedRecordIds[]", id);
  return q;
}

function mapRecord(ctx: TableContext, fields: string[], record: TeableRecord): SqlRow {
  const row: SqlRow = { __id: record.id };
  for (const appName of fields) {
    if (appName === "__id") continue;
    const meta = lookupField(ctx, appName);
    if (!meta) continue;
    let v = record.fields[meta.real];
    if (typeof v === "string" && meta.enumOut && Object.prototype.hasOwnProperty.call(meta.enumOut, v)) {
      v = meta.enumOut[v];
    }
    row[appName] = v;
  }
  return row;
}

async function executeSelect(ast: SelectAst): Promise<SqlRow[]> {
  const ctx = resolveTable(ast.table);
  const compiled = await compileWhere(ctx, ast.where);

  if (ast.kind === "count") {
    const alias = ast.alias ?? "count";
    if (compiled.skipAll) return [{ [alias]: 0 }];
    if (compiled.selectedIds.length > 0) {
      const q = buildQueryParams({ fieldKeyType: "name", selectedIds: compiled.selectedIds, take: 10_000 });
      const res = await teableFetch<TeableRecordResponse>(`/table/${ctx.tableId}/record?${q}`);
      return [{ [alias]: res.records.length }];
    }
    const q = buildQueryParams({ filter: compiled.predicates });
    const res = await teableFetch<{ rowCount: number }>(
      `/table/${ctx.tableId}/aggregation/row-count?${q}`,
    );
    return [{ [alias]: res.rowCount }];
  }

  if (compiled.skipAll) return [];

  const q = buildQueryParams({
    fieldKeyType: "name",
    signedUrl: "true",
    filter: compiled.predicates,
    orderBy: compiledOrderBy(ctx, ast.orderBy),
    take: ast.limit,
    skip: ast.offset,
    selectedIds: compiled.selectedIds,
  });
  const res = await teableFetch<TeableRecordResponse>(`/table/${ctx.tableId}/record?${q}`);
  return res.records.map((record) => mapRecord(ctx, ast.fields, record));
}

/* ------------------------------------------------------------------ */
/* Writes                                                              */
/* ------------------------------------------------------------------ */

interface TeableCreateResponse {
  records: Array<{ id: string }>;
}

function mapWriteFields(ctx: TableContext, data: Record<string, unknown>): Record<string, unknown> {
  const fields: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data ?? {})) {
    if (!key || key === "__id" || value === undefined) continue;
    const meta = lookupField(ctx, key);
    if (!meta) {
      // Structured app objects (e.g. PropertyRecord.location) cannot be written
      // as-is and are skipped rather than creating garbage fields.
      if (value !== null && typeof value === "object" && !Array.isArray(value)) continue;
      throw new Error(`TeableClient: no field mapping for "${key}" on table ${ctx.tableId}`);
    }
    // Computed fields are read-only.
    if (meta.type === "createdTime" || meta.type === "lastModifiedTime") continue;
    if (value === null) {
      fields[meta.real] = null;
      continue;
    }
    let v = value;
    if (typeof v === "string" && meta.enumIn && Object.prototype.hasOwnProperty.call(meta.enumIn, v)) {
      v = meta.enumIn[v];
    }
    fields[meta.real] = v;
  }
  return fields;
}

function assertWriteAllowed(): void {
  if (!isSafeWriteAllowed()) {
    throw new Error("TeableClient: writes are disabled (TEABLE_ALLOW_WRITE=false)");
  }
}

/* ------------------------------------------------------------------ */
/* Public client                                                       */
/* ------------------------------------------------------------------ */

export class TeableClient {
  constructor(_config?: unknown) {}

  async runSql<T>(sql?: string, _params?: unknown[]): Promise<T[]> {
    if (!sql) return [] as T[];
    const ast = new SqlParser(sql).parse();
    return (await executeSelect(ast)) as T[];
  }

  async createRecord(table: string, data: unknown): Promise<{ id: string }> {
    assertWriteAllowed();
    const ctx = resolveTable(table);
    const fields = mapWriteFields(ctx, data as Record<string, unknown>);
    const res = await teableFetch<TeableCreateResponse>(`/table/${ctx.tableId}/record`, {
      method: "POST",
      body: JSON.stringify({ records: [{ fields }], typecast: true }),
    });
    return { id: res.records?.[0]?.id ?? "" };
  }

  async updateRecord(table: string, id: string, data: unknown): Promise<{ id: string }> {
    assertWriteAllowed();
    const ctx = resolveTable(table);
    const fields = mapWriteFields(ctx, data as Record<string, unknown>);
    await teableFetch<unknown>(`/table/${ctx.tableId}/record`, {
      method: "PATCH",
      body: JSON.stringify({ records: [{ id, fields }] }),
    });
    return { id };
  }
}
